#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""The assistant's capability sections (docs/59): what the executor (the Codex task agent) can do on
this phone, in agent/assistant/prompts/capabilities.yaml, written into the three prompts that need it,
each in its model's voice:

  agent.md     the task agent: use it when ..., and the skill that tells how
  phone.md     the full-duplex voice model: the executor can ..., start or offer a task when ...
  realtime.md  the push-to-talk voice model: the same, as things it does through execution

Each prompt keeps its section between two markers; the rest of the prompt is written by hand.

  agent_capabilities.py render [--write]   print the prompts that would change (--write writes them)
  agent_capabilities.py check              exit 1 while a prompt is out of date
"""
import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / 'agent/assistant/prompts'
SOURCE = PROMPTS / 'capabilities.yaml'
BEGIN = ('<!-- capabilities: generated by tools/agent_capabilities.py render --write from capabilities.yaml. '
         'Edit that file, not this section. -->')
END = '<!-- /capabilities -->'
SECTION = re.compile(re.escape(BEGIN.split(':')[0]) + r':[^\n]*-->\n.*?' + re.escape(END), re.S)

# The text before the list, and how each item reads, per prompt.
INTRO = {
    'agent.md': 'Use a capability when a request fits it, also when the user does not name it. '
                'Before you use one, read the skill that "How" names.',
    'phone.md': 'The executor can do these things. Start a task when a clear request fits one, also when\n'
                'the user does not name it. When the situation fits one, you can offer it (see Proactive).',
    'realtime.md': 'You can do these things through execution. Send a request to execution when it fits one, also when '
                   'the user does not name it. When the situation fits one, you can offer it (see Proactive).',
}
BULLET = {'agent.md': '-', 'phone.md': '-', 'realtime.md': '*'}
# After an entry with `external` ("Sending"): that part needs the user's go-ahead.
EXTERNAL = {
    'agent.md': ' {} has an external effect: do it only on the user\'s explicit request or "yes".',
    'phone.md': ' {} needs the user\'s go-ahead.',
    'realtime.md': ' {} needs the user\'s go-ahead.',
}


def load(path=SOURCE):
    entries = yaml.safe_load(Path(path).read_text())['capabilities']
    for entry in entries:
        missing = {'name', 'can', 'when', 'how'} - entry.keys()
        if missing:
            raise ValueError(f'{path}: {entry.get("name", entry)} has no {", ".join(sorted(missing))}')
    return entries


def sentence(text):
    text = ' '.join(str(text).split())
    return text if text.endswith(('.', '!', '?')) else text + '.'


def item(prompt, entry):
    if prompt == 'agent.md':
        line = f'**{entry["name"]}**: {sentence(entry["can"])} Use when: {sentence(entry["when"])} How: {sentence(entry["how"])}'
    else:
        line = f'{entry["name"]}: {sentence(entry["can"])} When: {sentence(entry["when"])}'
    if entry.get('external'):
        line += EXTERNAL[prompt].format(' '.join(str(entry['external']).split()))
    return f'{BULLET[prompt]} {line}'


def section(prompt, entries):
    return '\n'.join([BEGIN, INTRO[prompt], *(item(prompt, e) for e in entries), END])


def rendered(text, prompt, entries):
    """The prompt with its section replaced; a prompt without the markers is an error."""
    if not SECTION.search(text):
        raise ValueError(f'{prompt}: no capability section ({BEGIN.split(":")[0]} ... {END})')
    return SECTION.sub(lambda _: section(prompt, entries), text, count=1)


def stale(prompts=PROMPTS, source=SOURCE):
    """{name: new text} of every prompt whose section differs from the source."""
    entries = load(source)
    out = {}
    for prompt in INTRO:
        path = Path(prompts) / prompt
        text = path.read_text()
        new = rendered(text, prompt, entries)
        if new != text:
            out[prompt] = new
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)
    render = sub.add_parser('render')
    render.add_argument('--write', action='store_true')
    sub.add_parser('check')
    args = parser.parse_args(argv)
    changed = stale()
    if args.command == 'check':
        for prompt in changed:
            print(f'agent/assistant/prompts/{prompt} is out of date: tools/agent_capabilities.py render --write',
                  file=sys.stderr)
        return 1 if changed else 0
    for prompt, text in changed.items():
        if args.write:
            (PROMPTS / prompt).write_text(text)
            print(f'wrote agent/assistant/prompts/{prompt}')
        else:
            sys.stdout.write(f'==> {prompt}\n{text}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
